### ISSUE TITLE
This is the same as ValueNotifier<int>

### ISSUE THREAD

**Issue by JCKodel** [josiahsrc/flutter_zustand#1]
And `ValueNotifier` doesn't even need `BuildContext`.

So, why bother?

```dart
final class Counter {
  const Counter();

  final count = ValueNotifier<int>(0);

  void incrementCount() {
    count.value++;
  }
}

...

const counter = Counter();

ValueListenableBuilder<int>(
   valueListenable: counter.count,
              builder: (BuildContext context, int value, _)
...
```

**Comment by josiahsrc** [comment]
Hey @JCKodel 👋 

I appreciate the feedback. ValueNotifier and ValueListenableBuilder are great classes for small-scale state management. However they have some baggage imho

1. You have to dispose them manually (boilerplate)
2. You have to specify a builder (boilerplate)
3. If you want to listen to state changes, you have to add listeners and dispose of them manually (boilerplate)
4. If count were a struct of two elements (a and b), you can't observe atomic changes to only one of those

**Comment by josiahsrc** [comment]
Closing this. Lmk if there's any more questions!
