### ISSUE TITLE
How persist in localStorage or FLutterdocument

### ISSUE THREAD

**Issue by samuk190** [josiahsrc/flutter_zustand#4]
I know the approach for flutter redux, but for zustand flutter is not very well  documented.

**Comment by josiahsrc** [comment]
Flutter zustand is a pretty new package, so a lot of things haven't been tried or documented.

For local storage you can create a wrapper around the set function. Something like this

```
class BearStore extends Store<int> {
  BearStore() : super(0) {
    init()
  }

  init() async {
    // load from shared prefs
    final s = await loadFromSharedPrefs();
    set(s);
  }

  persistedSet(int state) async {
    await setShwredPrefsValue(state);
    set(state);
  }
}
```

There's probably a good generalization in there somewhere, but that should get started. Hope that helps!
