### ISSUE TITLE
Persisting the state ?

### ISSUE THREAD

**Issue by squalvj** [josiahsrc/flutter_zustand#5]
Hey awesome lib btw, Im migrating my project to use this library!

I wonder if there are any plan to have a persistence data whenever the app is closed.
Looking forward for it 🙂

**Comment by josiahsrc** [comment]
Thanks, glad it helps! What state management system are you migrating from?

I don't have any plans for adding built-in persistence yet. There's a few basic implementations you can do though. E.g. you can create a base `PersistentStore` that handles all the serialization logic.

```dart
abstract class PersistentStore<T> extends Store<T> {
  PersistentStore(T initialState) : super(initialState) {
    _init();
  }

  Future<void> _init() async {
    final loaded = await load();
    if (loaded != null) {
      set(loaded);
    }
  }

  Future<T?> load();

  Future<void> save(T state);

  @override
  @mustCallSuper
  Future<void> dispose() async {
    await save(state);
    await super.dispose();
  }
}
```

Then extend that store in cases where you want data to persist. In this example I used shared prefs, but you can use hive or anything else.

```dart
class PersistentBearStore extends PersistentStore<int> {
  PersistentBearStore() : super(0);

  void increasePopulation() => set(state + 1);
  void removeAllBears() => set(0);
  
  @override
  Future<int?> load() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getInt('bears');
  }
  
  @override
  Future<void> save(int state) {
    final prefs = await SharedPreferences.getInstance();
    return prefs.setInt('bears', state);
  }
}
```

**Comment by squalvj** [comment]
Super useful!
Initially I Provider but I saw zustand from youtube in React and was so excited found in Flutter version!

It's wild this library works in a way its very simple!
Thanks for the example, very helpful.
